" Plugins jetzt mit junegunn/vim-plug managen
call plug#begin()
" git plugin
Plug 'tpope/vim-fugitive'
" Python completion und mehr
Plug 'davidhalter/jedi-vim'
" HübscherVerzeichnisbaum
Plug 'scrooloose/nerdtree'
" Unterstützung zum Ausführen von py.test
Plug 'alfredodeza/pytest.vim'
" Sinnvolle vim Voreinstellungen
Plug 'tpope/vim-sensible'
" Syntaxchecker für viele Sprachen
Plug 'vim-syntastic/syntastic'
" Initialize plugin system
call plug#end()

if has("autocmd")
  au BufReadPost * if line("'\"") > 0 && line("'\"") <= line("$")
    \| exe "normal! g'\"" | endif
  " .vimrc nach Änderung automatisch wieder laden
  autocmd bufwritepost .vimrc source $MYVIMRC
endif

colorscheme smyck

set encoding=utf-8
set showcmd " Show (partial) command in status line.
set showmatch " Show matching brackets.
set ignorecase
set smartcase " Do smart case matching
set autowrite " Automatically save before commands like :next and :make
set hidden " Hide buffers when they are abandoned
set mouse=a " Enable mouse usage (all modes) in terminals
set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab
set noswapfile

" Sichtbarer whitespace
set listchars=tab:▸\ ,eol:¬
" Shortcut um Anzeige von whitspace zu togglen
nmap <leader>l :set list!<CR>

if has("gui")
  set guioptions-=T   " Toolbar ausblenden
endif

" Sinnvolle Bindungen für deutsche Tastaturen
map ü <C-]>
map ö [
map ä ]
map Ö {
map Ä }
map ß /

let maplocalleader = ","
let mapleader = ","


set statusline=%<%f\ %h%m%r%{fugitive#statusline()}%=%-14.(%l,%c%V%)\ %P
